inherit_gem:
    rubocop-shopify: rubocop.yml

require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  UseCache: true
  CacheRootDirectory: tmp
  Exclude:
    - 'test/fixtures/**/*'

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: true
  IgnoredMethods:
  - require
  - require_relative
  - require_dependency
  - yield
  - raise
  Exclude:
  - Gemfile

Style/StringLiterals:
  EnforcedStyle: double_quotes
